export const ProfileViewModeEnum = {
  PRIVATE: 0,
  PUBLIC: 1,
};

export const ProfileUpdateFreelancerParamEnum = {
  CV_UPLOAD: "CV_UPLOAD",
  PERSONAL_INFORMATION: "PERSONAL_INFORMATION",
  EMPLOYEMENT_HISTORY: "EMPLOYEMENT_HISTORY",
  PROFESSIONAL_INFORMATION: "PROFESSIONAL_INFORMATION",
  SOCIAL_ACCOUNTS: "SOCIAL_ACCOUNTS",
  ACCOUNT_SECURITY: "ACCOUNT_SECURITY",
  CHARGES: "CHARGES",
};

export const ProfileUpdateFreelancerViewModeEnum = {
  FULL: "FULL",
  CURRENT: "CURRENT",
  TITLE: "TITLE",
  BIOGRAPHY: "BIOGRAPHY",
  PROFILE_PICTURE: "PROFILE_PICTURE",
  PITCH_VIDEO: "PITCH_VIDEO",
  LANGUAGES: "LANGUAGES",
  EMPLOYEMENT_HISTORY: "EMPLOYEMENT_HISTORY",
  CERTIFICATIONS: "CERTIFICATIONS",
  SKILLS: "SKILLS",
  EDUCATIONS: "EDUCATIONS",
  CATEGORIES: "CATEGORIES",
  SOCAIL_ACCOUNTS: "SOCAIL_ACCOUNTS",
  PHONE_NUMBERS: "PHONE_NUMBERS",
};
