export const RouteEnum = {
  HOME: "/",
  VISA: "/visa",
  ABOUT_US: "/about-us",
  COACHING: "/coaching",
  PERSONALINFO: "/personal-info",

  LOGIN: "/login",
  SIGNUP: "/signup",
  SIGNUP_VERIFICATION_REQUEST: "/signup/verification-request",
  SIGNUP_VERIFICATION: "/signup/verification/:id/:otp",
  SIGNUP_CONGRATULATIONS: "/signup/congratulations",
  FORGOT_PASSWORD: "/forgot-password",
  CONTENT_CLIENT_GETTING_STARTED: "/getting-started",
  HOW_IT_WORKS: "/how-it-works",
  // CLIENTS: "/clients",
  // CLIENTS_DASHBOARD: "/clients/:id",
  // CLIENTS_PROFILE: "/clients/profile",
  // CLIENTS_PROFILE_UPDATE: "/clients/profile/update",
  // CLIENTS_HIRES: "/clients/my-hires",
  // FREELANCERS: "/freelancers",
  // FREELANCERS_DASHBOARD: "/freelancers/:id",
  // FREELANCERS_PROFILE: "/freelancers/profile",
  // FREELANCERS_PROFILE_UPDATE: "/freelancers/profile/update",
  // FREELANCERS_PROFILE_UPDATE_AVOID: "/freelancers/profile/update/avoid",
  // FREELANCERS_PROFILE_UPDATE_TIPS: "/freelancers/profile/update/tips",
  // FREELANCERS_STATS: "/freelancers/stats",
  // FREELANCERS_PROJECTS: "/freelancers/:id/projects",
  // FREELANCERS_PROJECTS_DASHBOARD: "/freelancers/project-dashboard",
  // FREELANCERS_RECENTLY_VIEWED: "/freelancers/recently-viewed",
  // FREELANCERS_SAVED: "/freelancers/saved",
  PROFILE: "/profile",
  PROFILE_STATS: "/profile/stats",
  PROFILE_FREELANCERS: "/profile/freelancers",
  PROFILE_FREELANCERS_DASHBOARD: "/profile/freelancers/:id",
  PROFILE_FREELANCERS_RECENTLY_VIEWED: "/profile/freelancers/recently-viewed",
  PROFILE_FREELANCERS_SAVED: "/profile/freelancers/saved",
  PROFILE_CLIENTS: "/profile/clients",
  PROFILE_CLIENTS_DASHBOARD: "/profile/clients/:id",
  PROFILE_DASHBOARD: "/profile/:id",
  PROFILE_UPDATE: "/profile/update",
  PROFILE_UPDATE_AVOID: "/profile/update/avoid",
  PROFILE_UPDATE_TIPS: "/profile/update/tips",
  SETTINGS: "/settings",
  SETTINGS_BILLING_AND_PAYMENTS: "/settings/billing-and-payments",
  SETTINGS_PASSWORD_AND_SECURITY: "/settings/password-and-security",
  SETTINGS_NOTIFICATION: "/settings/notification",
  PROJECTS: "/projects",
  PROJECTS_SEARCH: "/projects/search",
  PROJECTS_FREELANCER_DASHBOARD: "/projects/my-dashboard",
  PROJECTS_DASHBOARD: "/projects/:id",
  PROJECTS_CREATE: "/projects/create",
  PROJECTS_EDIT: "/projects/:id/edit",
  JOBS: "/jobs",
  JOBS_DASHBOARD: "/jobs/:id",
  JOBS_CREATE: "/jobs/create",
  JOBS_EDIT: "/jobs/:id/edit",
  JOBS_SEARCH: "/jobs/search",
  JOBS_SAVED: "/jobs/saved",
  JOBS_PROPOSALS: "/jobs/proposals",
  JOBS_CONTRACTS: "/jobs/contracts",
  JOBS_CLIENT_DASHBOARD: "/jobs/my-dashboard",
  JOBS_CLIENT_HIRES: "/jobs/my-hires",
  JOBS_CLIENT_POSTS: "/jobs/posts",
  JOBS_CLIENT_POSTS_ADD: "/jobs/posts/add",
  // JOBS_FREELANCER_DASHBOARD: "/jobs/my-dashboard",
  REPORTS: "/reports",
  REPORTS_OVERVIEW: "/reports/overview",
  REPORTS_SUMMARY: "/reports/summary",
  REPORTS_BILLINGS_AND_EARNINGS: "/reports/earnings",
  REPORTS_TRANSACTIONS: "/reports/transactions",
  REPORTS_BUDGETS: "/reports/budgets",
  MESSAGES: "/messages",
  MESSAGES_ROOMS: "/messages/rooms",
};
